### ISSUE TITLE
IIIF Image Delivery Service

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#11]
**STORY**
As a historian researching evolving representations of geospatial knowledge, I would like to be able to interact with resources like https://brbl-dl.library.yale.edu/vufind/Record/4360397?image_id=16173880, and manipulate them quickly*, in order to compare them with other maps and cartographic conventions.

*Quickly = system responds to pan, zoom, and rotate request in under 3 seconds

**ACCEPTANCE**
Given a manifest for a work that includes at least one image, 
- [ ] I can pan & zoom the image
- [ ] I can rotate the image
- [ ] The view on my screen (1980x180) redraws completely in under 3 seconds

**Comment by geekscruff** [comment]
For reference:

- https://hub.docker.com/r/lorisimageserver/loris (seems a bit old)
- https://hub.docker.com/search?q=cantaloupe&type=image (various options)
