### ISSUE TITLE
Mgmt UI Header

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1332]
**Story:** 

This ticket is for the creation of the header/navigation bar and the subnav bar for the Management app.  

NOTE: this will be a global header, as it will appear on every page of the management app. Look and feel will be consistent with the YUL DL).

**Acceptance:**

- [x] Create a main header/nav bar with the YUL brand.
     - [x] "Yale University Library" should be text
          - [x]  Font size 38 px 
          - [x]  Font type YaleNew
          - [x] Boarder 
               - [x] height 80 px
               - [x] color #043669 (dark blue)

- [x] Create a subheader/subnav bar with the name of the application 
    - [x] "Digital Library Management Portal" - or "application" should be text
        - [x]  Font size 30 px 
        - [x]  Font type Mallory reg (Open San) [maybe mallory book]
        - [x] color #043669 (dark blue)
    - [x] Boarder bottom 
         - [x] line color #043669 (dark blue)
             - [x] 40% opacity 

----
**Other Notes**
- [ ] Main navbar color: #043669 (Yale Blue); font: YaleNew Roman, semibold; font-size: 2em

**Comment by tmacmath** [comment]
Create a primary navbar (with Yale branding and styling) and secondary nav bar (with the name of the application).

**Comment by FCRodriguez7** [comment]
I attached an image below.   The font for the subheader is not the correct font. 

![Screen Shot 2021-06-03 at 12.28.26 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0ae7c83e-34d2-4664-9fe8-74ea27e52679)

**Comment by FCRodriguez7** [comment]
I noticed that the sidebar header text "Management" is deleted in the new design.   The sidebar text "Management" currently behaves as a home button.  Should the text "Digital Library Management" function as the home?

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/647

**Comment by FCRodriguez7** [comment]
Released management v2.41.0
