### ISSUE TITLE
Camerata Tech Debt

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#157]
**ISSUES**
- [ ] Create log groups on build to eliminate "Failed to create log group..." warnings
- [x] Automate LoadBalancer setup
- [x] Grant service role access to S3 to eliminate need for secrets
- [x] ? Logging configuration for both local dev & ecstatics
- [x] Containers should run with RAILS_ENV=development for dev, RAILS_ENV=test for CI, and RAILS+ENV=production for ECS
- [ ] De-dup SOLR_URL and SOLR_CORE
- [ ] Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4).
- [ ] Solr warning *** [WARN] *** Your open file limit is currently 1024. - It should be set to 65000 to avoid operational disruption.

**Comment by mark-dce** [comment]
Closing since we've covered a number of these already and shifted to the practice of using chores to handle refactoring and other process improvement that we can prioritize within the scope of active sprints.
