### ISSUE TITLE
Add minimal fields needed to associate Parent and Child objects with Preservica for sync

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1755]
**Epic**

A few fields will be needed to maintain the association of Parent and Child objects with Preservica for the purposes of the Preservica sync.  These might include:
- File source (DCS or Preservica)
- Preservica ID (or Preservica asset ID?)
- Last sync timestamp

**Tasks**
- [ ] Identify required fields
- [ ] Add to Parent and Child models
- [ ] Add to display forms
- [ ] Add to edit forms (if required)
- [ ] Add to datatables
