### ISSUE TITLE
[DISCUSS] Requirements Gathering for Upcoming Development Work

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2098]
Discuss upcoming development work to provide a base level of understanding to move forward with requirements gathering. Michael could please give a primary on IIIF structural metadata and what we need to form requirements, and Martin to help provide more understanding around what we may need to facilitate Voyager digital object linking. 

- [x] IIIF Structural Metadata -- See #2103 
- [x] Voyager linking
- [ ] Granular access controls -- See #2106
- [ ] Improved reporting and analytics -- See #2107
- [ ] Ability to set separate permissions for Full Text files to that of its parent  -- See #2108

**Comment by DraxIndustries79** [comment]
There's a Thurs 5/26 call planned for this

**Comment by sshetenhelm** [comment]
Met on 2022.05.26 for initial discussions. See #2103 for future requirements work.

**Comment by motropuk** [comment]
Notes from intial meeting today https://docs.google.com/document/d/191Kz52V-YoramZLiMoRVWsmrIoi39SLr_sZgIDPRJmY/edit#heading=h.zbhc8sbddr49

Focused on IIIF structural metadata work today and Voyager linking. Other topics to address
