### ISSUE TITLE
Create Permission Set "show" page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2230]
**Story**

As a user  I'd like to see the details of a permission set displayed (i.e., not in a form).

**Acceptance**

- [x] Create a display page for the individual Permission Set, modeled on the form created in #2226
- [x] Make this page the one the user sees when navigating from the list of Permission Sets created in #2212
- [x] Page has a "back" button that leads back to the list of Permission Sets created in #2212
- [x] Page has an Edit button, visible to Permission Set Administrators and System Admins, that links to the edit form created in #2226

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1075

**Comment by martinlovell** [comment]
v2.59.66

**Comment by motropuk** [comment]
JP demo on Friday standup
