### ISSUE TITLE
Implement new parent object show page

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2372]
# Summary
Implement new design of parent object show page

# Acceptance Criteria
- [x] field values are resorted to match attached screenshot from ticket #2365
- [x] labels will be #7b736b color and 14px font size
- [x] field values will be #7b736b and 14px font size
- [x] alternating table background colors are #ffffff and #f2f2f2
- [x] border is 2 px wide and #dee2e6 color
- [x] filter icon (see below) in top left corner
- [x] filter action clears fields with no value
- [x] font family for page is Mallory-Medium

### Filter Icon
- [x] when in unfiltered state `fa-filter`
-- font-size: 28px;
-- color: #343A40;
-- border: 5px solid #CCC;
-- padding: 5px;
-- border-radius: 5px;
- [x] when in filtered state `fa-filter-circle-xmark`
-- font-size: 27px;
-- color: #343A40;
-- border: 5px solid #CCC;
-- padding: 5px;
-- border-radius: 5px;

**Comment by tmacmath** [comment]
Icon files forthcoming.

**Comment by tmacmath** [comment]
@K8Sewell Here you go!

**Comment by tmacmath** [comment]
Anything happening with this? Still in backlog?

**Comment by K8Sewell** [comment]
Hi @tmacmath , we don't have a Pro account for font awesome - would you please provide an alternate when you have a chance?  

Generally, unless a ticket is in the 'In Progress' column it means work isn't actively being done on it.  Also, our process has been that a person usually assigns themself a ticket when they are actively working on it so other's know not to pick it up.  I'm going to unassign myself for now so anyone can pick up this ticket while I finish up the two tickets I'm working on currently.

**Comment by motropuk** [comment]
@tmacmath will look into pro account for font awesome to see if we have this at Yale. If we dont, we need an alternative font. Need this before we move into Sprint

**Comment by tmacmath** [comment]
Looking to see if we have a Pro account. LIT doesn't seem to have used Font Awesome icons for Quicksearch, as we did in the past. They used SVG icons for the redesign. It would be much easier to use the free filter icons - see info below (copied from an HTML file). 


<script src="https://kit.fontawesome.com/b9b69d7c88.js" crossorigin="anonymous"></script>


<i class="fa-solid fa-filter"></i>
<i class="fa-solid fa-filter-circle-xmark"></i>



i.fa-solid.fa-filter {font-size: 28px; color: #343a40; border: 5px solid #ccc; padding: 5px; border-radius: 5px;}
i.fa-solid.fa-filter-circle-xmark {font-size: 27px; color: #343a40; border: 5px solid #ccc; padding: 5px; border-radius: 5px;}

**Comment by K8Sewell** [comment]
I think we may need an alternate icon for the `fa-filter-circle-xmark` because it displays as an alternating '!' and '?' in a circle.  Unless that's the intended design in which case we can ignore this.



![Image](https://user-images.githubusercontent.com/36549923/228026204-ef2cca3b-db25-40e1-9d87-1d42f26d9ff5.png)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1164

**Comment by martinlovell** [comment]
v2.59.99

**Comment by tmacmath** [comment]
Looks great on test - I think I like a 3px border on the filter button better, though.
