### ISSUE TITLE
Link to Digital Collections Help Guide from Advanced Search page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2647]
After page is created via #2646 

**Story**
We want to add a content section on the Advanced Search page that points to the Digital Collection help guide page. The section will 

- Have a header that states 'More Information'
- Include the text "For help using this site, please see the Digital Collections Help Guide."
- Link to the Digital Collection Help Guide from the phrase "Digital Collections Help Guide."

The section should utilize the following formatting:

- The header "More information" is an h2; font is YaleNew-Roman. Same font color as the Advanced Search h2 above it (#043669)
- Text font is MalloryMP-Medium; font size is 14px; font color is #7b736b.
- Text should be left-aligned with the header as pictured.
- Testing should be done on mobile devices when the work is completed.
- Additionally, the h1 page title font (Advanced Search) should be YaleNew-Roman.

Screenshot: 
In comments

**Acceptance**
- [x] Add content section under 'Advanced Search Tips' on [Advanced Search page](https://collections.library.yale.edu/advanced)
- [x] Add header for this section stating 'More Information' 
  - [x] header is h2; font is YaleNew-Roman; color is #043669
- [x] Added text under 'More Information' header that states "For help using this site, please see the Digital Collections Help Guide."
  - [x] Text font is MalloryMP-Medium; font size is 14px; font color is #7b736b; text is left-aligned with header
- [x] Linked to Digital Collections Help Guide page (created via #2646 ) from phrase "Digital Collections Help Guide."
- [x] h1 page title (Advanced Search) font updated to YaleNew-Roman
- [x] Testing should be done on mobile devices before being rolled out.

**Comment by tmacmath** [comment]
Here are the specs with an attached screenshot (which was mocked up in the browser): 

- The header "More information" is an h2; font is YaleNew-Roman. Same font color as the Advanced Search h2 above it (#043669)
- Text font is MalloryMP-Medium; font size is 14px; font color is #7b736b. 
- Text should be left-aligned with the header as pictured. 
- Testing should be done on mobile devices when the work is completed.

**Comment by tmacmath** [comment]
![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/87bf039b-db4e-4e1b-9d0c-df537523d383)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/937

**Comment by jpengst** [comment]
Deployed to Test v1.60.86

**Comment by sshetenhelm** [comment]
Looks good to me on test!
