### ISSUE TITLE
OwP: Blacklight User Requests Page MVP

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2724]
**Story**
Users should have a page in Blacklight where they can view the status of their requests for permission to view objects. This should be a separate page from the holistic bookmark page. 

The page should feature a table with four columns: Title, Call Number, Request Date, Status, and Access Expires.

The specs for the page were sourced from #2594 and are repeated in acceptance in this ticket.

**NOTE ON MOCKUP** - This was a beautiful mockup that I then destroyed because I forgot to ask for a fifth column and a button back to the bookmarks list. Please note that the font for "Access Expires" should be the same as the rest of the table. The button should be formatted the same as the rest of the buttons throughout DCS.

Mockup:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/8cb7dfb5-93aa-4fd6-a948-17221c6acee2)

**Acceptance**

Page
- [x] Create `requests` page - url `/permission_requests`
- [x] Header states Digital Access Requests
- [x] Header has following formatting: A. 35px; #043669; YaleDisplay-Roman; border-bottom: none; --- [NOTE: used 2.1rem instead of 35px for enhanced responsiveness]
- [x] Add Bookmark Button - link to `/bookmarks` 

Requests Table
- [x] Table has five columns titled Title, Call Number, Request Date, Status, and Access Expires
- [ ] B. Table font: Mallory Medium, 16pt (default link color) --- [NOTE: did not do this because the header and body font sizes, below, would override this anyway]
- [x] C. Links: object title should link to the object in the DL; regular link color
- [x] D. Table zebra striping: #ffffff; alternating with #f2f2f2; (same as the table in the management app) --- [NOTE: #f2f2f2 wasn't in our colors so I kept the default bootstrap styling of white and light grey (rgba(0, 0, 0, 0.05))]
- [x] E. Table border: 1px solid #dee2e6; --- [NOTE: #dee2e6 wasn't in our colors so I used our medium grey #7b736b]
- [x] F. Table header/field labels: font-size: 18px; font-family: Mallory-Medium; font-color: #043669; --- [NOTE: used 1.1rem instead of 18px for enhanced responsiveness]
- [x] G. For table values that are not links: font-family: Mallory-Medium (400); font-size: 14px; font-color: #222529; --- [NOTE: used .9rem instead of 14px for enhanced responsiveness && #222529 was not in our colors so I used our darkest grey #222222 instead]
- [x] H. For the sort icon, use Font Awesome or Bootstrap Glyphicons -  _Tracy will provide a link to it, and if those don’t work well, she'll find something else._ --- [NOTE: nothing provided so I used the double arrow icon we use to denote sorting on the search results page]
- [x] Table is sortable for every column

Requests Table Data
- [x] Title column displays title of object for which permission has been requests & links to that object's show page
- [x] Call Number column displays call number of said object
- [x] Request Date displays the date a user requests permission
- [x] Status displays information regarding whether a request is pending, approved, or denied
- [x] Access Expires displays 'N/A' for objects with a status of Pending or Denied
- [x] Access Expires displays date that permission to view an object expires

**Comment by K8Sewell** [comment]
![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/dcb59650-3a1d-4847-b0dc-408f2b6e0dae)

**Comment by K8Sewell** [comment]
PRs ready for review:

Management - https://github.com/yalelibrary/yul-dc-management/pull/1325
Blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/968

**Comment by K8Sewell** [comment]
Deployed to Demo with [OwP_FeatureBranch](https://github.com/yalelibrary/yul-dc-blacklight/pull/931)

**Comment by K8Sewell** [comment]
Redirect and notification work as expected as a not logged in user.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/f7806753-6132-4d4a-913b-3674d299c1b5)



Unfortunately, the current auth error with OpenId is keeping me from checking out the logged in version of what this will look like.  Will update ticket when log in issues are resolved.

**Comment by K8Sewell** [comment]
Now that log in is fixed (thanks, @jpengst! ) this is looking as expected on Demo.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/0a30e4b7-4ad1-46f8-a09a-6f784bf7522a)

**Comment by sshetenhelm** [comment]
Confirming that table looks great and works as expecting (linking out, sorting, etc.). 

@tmacmath are you happy with the 'Back to Bookmarks' button placement or would you recommend it somewhere else?
