### ISSUE TITLE
Set up continuous deployment cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#329]
**STORY**
As a service owner, I'd like to know my application is deployable without having to manually deploy it, so that I don't have to anticipate unplanned work when deploying to production-like environments.

**ACCEPTANCE**
- [x] We have a process that tests deployability of the ecosystem on a regularly scheduled basis
- [x] The process runs the deploy_spec tests
- [x] If either deployment or the test suite fails, a notification is sent to selected team members

**Comment by mark-dce** [comment]
@fnibbit I got the notification - awesome!

<img width="603" alt="image" src="https://user-images.githubusercontent.com/3064318/92662727-113e5c00-f2c5-11ea-8ca4-ba713d72764b.png">
