### ISSUE TITLE
SPIKE: Ingest 500 Sample Objects

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#458]
**ACCEPTANCE**
Given a list of Parent OIDS, identify the gaps to
- [ ] Create the parent object 
- [ ] Get metadata from the Metadata Cloud, save it to the Parent, and index it to Solr
- [ ] Read child OIDs from the Metadata Cloud and create child objects
- [ ] Locate the access master for each child OID and generate the corresponding PTIFF
- [ ] Save the PTIFF to S3
- [ ] Generate a manifest for the parent that points to each of the child images

**Comment by orangewolf** [comment]
I was able to upload a CSV with OIDs and see ladybird Metadata cloud info loaded for them (via VPN). I can switch those objects to different metadata sources and see them update / reindex.  The manifests do not generate right now (we have a few tickets around that), but PTIFFs do if your master path is right. The proxy / manifest / image parts do not line up right, which means the current process sort of peters out on the last two steps.

## Questions and Assumptions ##
- Do only need to index in solr if the metadata cloud job has run? 
- Is it true that Child objects will only come from Ladybird?


## TODO ##
- end to end error reporting with work queue (see #500, #366)
- CSV entries for non-ladybird records (is this needed right now? it is very easy to do. There used to be a ticket, but it seems to be gone)
- read json / trigger ptfs / create manifest /index in solr when authoriative_metadata_source changes (#520)
- need a way to regenerate ptfs (*)
- temp_workspace needs to be correct file path (*)
- files need to be output in pairtree (#508, #473)
- need to generate manifests automatically and only generate index afterward (#509, #511)
- adding generated images to the manifest failed for me (on IiifPresentation#47)
