### ISSUE TITLE
Batch Job Status Pages

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#632]
**STORY**
As a librarian importing works into the DL, I'd like an easy way to understand that status of my job, so that I can easily tell if the import was successful or if there's some action I need to take.

**ACCEPTANCE**
- [ ] I can visit a batch job status overview where I can
   - [ ] Confirm the job was submitted as expected
   - [ ] See where my job is in relation to other people's jobs
   - [ ] See if the job's status (pending, in-progress, completed, errored)

- [ ] I can drill-down into a specific job and see
   - [ ] The original import file (name + plus link to view the file)
   - [ ] Detailed job status
   - [ ] Item details for each child work

![User^ TimEs ITems.jpg](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/a15740cc-5e5f-4a15-98f8-438b2eedd230)

![BATCH JOB View (Su30).jpg](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/af05a3a2-1ffb-4b67-bcee-54f515063ede)

**Comment by mark-dce** [comment]
Superseded by #653
