### ISSUE TITLE
Parent Object Design Decisions (DRAFT)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#669]
The DL is the system of record for certain fields, and the Parent Object needs to save certain fields it pulls from LB/Goobi

Parent Object needs to save:
- [ ] OID
- [ ] Extent of Digitization
- [ ] Rights Statement
- [ ] Viewing Direction (IIIF)
- [ ] Display Layout (IIIF)

Parent Object should NOT allow import if the following are missing:
- [ ] OID
- [ ] Rights Statement

Parent Object needs to validate the following:
- [ ] Extent of Digitization (nil should become default value, list on ticket)
- [ ] Viewing Direction (nil allowed, no default value, list on ticket)
- [ ] Display Layout (nil allowed, no default value, list on ticket)

I should be able to update the following things in Parent Object UI (edit screen):
- [ ] Extent of Digitization
- [ ] Rights Statement
- [ ] Viewing Direction (IIIF)
- [ ] Display Layout (IIIF)

Parent Object import gives error/fails in UI if OID already exists (right now I get a rails error screen, but I mean like a nice error on the page like if you leave out a required thing)
