### ISSUE TITLE
Image migration tracking app

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#67]
**STORY**
As a project stakeholder, I would like a way to know how far we are in the image migration process, so that I can forecast when it will be done and track-down any images that have issues

**ACCEPTANCE**
We have an application the team can access that tracks
- [ ] the OID for all images to be migrated
- [ ] the source path and filename of the access master once it has been identified
- [ ] the destination path and filename of the access master once it has been copied
- [ ] the checksum of the file 
- [ ] an optional tracking note for each image
In the application
- [ ] I can filter/search by OID - i.e. I can look up a specific migration record
- [ ] I can filter by images that have not been moved - e.g. destination path is empty
The application has a reporting function that shows
- [ ] Total # of known images
- [ ] Number of identified access masters
- [ ] Number of migrated images
Access
- [ ] Add DCE/Notch8 NetIDs to access list

**Comment by FCRodriguez7** [comment]
There's a meeting scheduled for Thursday.
