### ISSUE TITLE
Discovery Access Restrictions (Yale Community Only items)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#707]
**STORY**
In order to ensure compliance with intellectual property rights, restrictions, and agreements, the system needs to enforce access restrictions for non-public works.

Initially works will fall into three categories
* Public (full public access to metadata, manifests, and images)
* Yale Community (metadata is visible, manifests and images are restricted to yale accounts and/or network connected devices)
* All other (fully restricted by the discovery, manifest, and image services) 
*NOTE: additional access levels will be rolled out in phase 2 and later*

**DECISIONS**
* Serve manifests and images from the collections.library.yale.edu domain (not iii.library.yale.edu)
manifests : collections.library.yale.edu/manifests
    * iiif : 
        Version 2.x API : collections.library.yale.edu/image/iiif/2
        Version 3.x API : collections.library.yale.edu/image/iiif/3
* Confirm DL stand-alone Mirador behaves as expected (i.e. like integrated UV in blacklight)
collections.library.yale.edu/mirador
* Yale-only works will not be viewable in third party image viewers

Open Question: is there a time limit on the session duration that might have end-user impact (i.e. browsing manifests w/o touching blacklight to extend session time)

**ACCEPTANCE**
Access restrictions are enforces
- [ ] In the discovery application
- [ ] By the manifest service
- [ ] By the image service

**BACKGROUND**
See the full decision history captured in https://docs.google.com/document/d/1pwjxb5aVBNYqqkmlye6wdvNlz6eeZt0RyWpuS2t5eKE/edit#
