### ISSUE TITLE
Performance Testing & Remediation

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#719]
**STORY**
We want to ensure that the new system will easily handle the level of traffic seen on the current BRBL site with plenty of headroom for additional use.

**ACCETPANCE**
- [ ] Identify traffic baselines from current system
   - [ ] Search
   - [ ] Metadata view
   - [ ] Image access
   - [ ] Pan & Zoom 
- [ ] Test for current performance of new system
   - [ ] Search
   - [ ] Metadata view
   - [ ] Image access
   - [ ] Pan & Zoom 
- [ ] Determine how much additional traffic we want the system to initially support
- [ ] Make remediation to handle the initial desired traffic levels
   - [ ] Re-test to ensure goals are met
