### ISSUE TITLE
Security Testing & Remediation

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#720]
**STORY**
We want to ensure that the new system will meet security requirements and standards set by LIT and ITS.

**ACCETPANCE**
- [ ] Identify testing requirements and milestones
- [ ] Test existing staging system
- [ ] Make remediation to any vulnerabilities found
   - [ ] to staging
   - [ ] to production
- [ ] Repeat tests against staging until not security issues remain
- [ ] Ensure all changes are propagated to production
- [ ] Conduct final production security review and testing
