### ISSUE TITLE
Schedule DNS cutover of brbl-dl.library.yale.edu

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#997]
Work with ITS to schedule the DNS cutover for the morning of the 27th.    We need help from DevOps to flesh out the task list below.

**Tasks for day of cutover**
- [x] New DNS record brbl-legacy-dl.library.yale.edu created for brbl-dl.library.yale.edu
- [x] brbl-dl.library.yale.edu alias added to the redirect application
- [x] Verify http -> https redirect in place for brbl-dl.library.yale.edu for the redirect app
- [x] Verify that TLS certificate for brbl-dl.library.yale.edu is in place for the redirect app

**Comment by ra359** [comment]
Created ticket for hostmaster to create new record:

INC1930165 New internal/external DNS record for brbl-legacy-dl.library.yale.edu

**Comment by ra359** [comment]
Clarification, goal of this tkt is to have https://brbl-dl.library.yale.edu point to the app at https://collection-redirects.library.yale.edu/

**Comment by ra359** [comment]
Test and prod linkk:
https://brbl-dl-test.library.yale.edu/vufind/Search/Results?lookfor=GEN_MSS_100&type=CallNumber&sort=title
https://brbl-dl.library.yale.edu/vufind/Search/Results?lookfor=GEN_MSS_100&type=CallNumber&sort=title
